# this is a copy/past of https://github.com/DPS2022/diffusion-posterior-sampling/blob/main/configs/diffusion_config.yaml

sampler: ddpm
steps: 1000
noise_schedule: linear
model_mean_type: epsilon
model_var_type: learned_range
dynamic_threshold: False
clip_denoised: True
rescale_timesteps: False
timestep_respacing: 1000
