# This is a copy/paste of https://github.com/DPS2022/diffusion-posterior-sampling/blob/main/configs/model_config.yaml

# Defaults for image training.

image_size: 256
num_channels: 128
num_res_blocks: 1
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
resblock_updown: True
use_fp16: False
use_new_attention_order: False

# put the absolute path of ffhq model weights
model_path:
